/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;
import dao.AbsenceDAO;
import dao.EmployeDAO;
import dao.TypeAbsenceDAO;
import entities.Absence;
import entities.Employe;
import entities.TypeAbsence;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import java.awt.*;
import java.awt.event.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
/**
 *
 * @author Mohamed EL MOUDEN
 */
public class MainAppGUI extends javax.swing.JFrame {
    static final Color BG_DARK       = new Color(13,  17,  23);
    static final Color BG_PANEL      = new Color(22,  27,  34);
    static final Color BG_CARD       = new Color(30,  37,  46);
    static final Color ACCENT_BLUE   = new Color(56,  139, 253);
    static final Color ACCENT_GREEN  = new Color(63,  185, 80);
    static final Color ACCENT_RED    = new Color(248, 81,  73);
    static final Color ACCENT_ORANGE = new Color(210, 153, 34);
    static final Color ACCENT_PURPLE = new Color(139, 92,  246);
    static final Color TEXT_PRIMARY  = new Color(230, 237, 243);
    static final Color TEXT_MUTED    = new Color(110, 118, 129);
    static final Color BORDER_COLOR  = new Color(48,  54,  61);

    static final Font FONT_TITLE = new Font("Segoe UI", Font.BOLD,  20);
    static final Font FONT_SMALL = new Font("Segoe UI", Font.PLAIN, 11);
    static final Font FONT_BTN   = new Font("Segoe UI", Font.BOLD,  13);
    static final Font FONT_TABLE = new Font("Segoe UI", Font.PLAIN, 13);
    static final SimpleDateFormat SDF = new SimpleDateFormat("yyyy-MM-dd");
private JPanel     centerPanel;
    private CardLayout cardLayout;
    private JLabel     lblCurrentPage;

    // Panel Employés
    private JTable            tblEmployes;
    private DefaultTableModel modelEmployes;
    private ModernTextField   txtEmpNom, txtEmpDepartement, txtEmpPoste;
    private JLabel            lblEmpStatus, lblEmpBadge;
    private int               selEmp = -1;

    // Panel Types
    private JTable            tblTypes;
    private DefaultTableModel modelTypes;
    private ModernTextField   txtTypeLibelle;
    private JLabel            lblTypeStatus, lblTypeBadge;
    private int               selType = -1;

    // Panel Absences
    private JTable                     tblAbsences;
    private DefaultTableModel          modelAbsences;
    private ModernTextField            txtAbsDebut, txtAbsFin;
    private ModernTextField            txtFiltreDebut, txtFiltreFin, txtFiltreDate;
    private JComboBox<Employe>         cmbEmploye;
    private JComboBox<TypeAbsence>     cmbType;
    private JComboBox<Object>          cmbFiltreType;
    private JLabel                     lblAbsStatus, lblAbsBadge;
    private int                        selAbs = -1;


    /**
     * Creates new form MainAppGUI
     */
    public MainAppGUI() {
        initComponents();
        setTitle("Gestion des Absences — RH");
        setSize(1100, 720);
        setMinimumSize(new Dimension(900, 600));
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setBackground(BG_DARK);
        getContentPane().setLayout(new BorderLayout()); // ← Remplace le GroupLayout de NetBeans

        // Construction de l'interface
       getContentPane().add(creerNavBar(), BorderLayout.NORTH);

        // Zone centrale avec CardLayout (un panel = une page)
        cardLayout  = new CardLayout();
        centerPanel = new JPanel(cardLayout);
        centerPanel.setBackground(BG_DARK);
        centerPanel.add(creerPanelEmployes(), "employes");
        centerPanel.add(creerPanelTypes(),    "types");
        centerPanel.add(creerPanelAbsences(), "absences");
        centerPanel.add(creerPanelStats(),    "stats");

        getContentPane().add(centerPanel, BorderLayout.CENTER);

        // Page affichée au démarrage
        cardLayout.show(centerPanel, "employes");
lblCurrentPage.setText("Employés  ");
        appliquerStyleGlobal();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 private JPanel creerNavBar() {
    JPanel nav = new JPanel(new BorderLayout());
    nav.setBackground(BG_PANEL);
    nav.setBorder(new MatteBorder(0, 0, 1, 0, BORDER_COLOR));

    // Logo gauche
    JLabel logo = new JLabel("  Gestion des Absences");
    logo.setFont(new Font("Segoe UI", Font.BOLD, 16));
    logo.setForeground(TEXT_PRIMARY);
    nav.add(logo, BorderLayout.WEST);

    // Popup menu déroulant
    JPopupMenu popup = new JPopupMenu();
    popup.setBackground(BG_CARD);
    popup.setBorder(new LineBorder(BORDER_COLOR, 1));

    String[][] items = {
    {"\uD83D\uDC64  Employ\u00e9s",       "employes",   "Employ\u00e9s"},
    {"\uD83D\uDCCB  Types d'absence", "types",      "Types d'absence"},
    {"\uD83D\uDCC5  Absences",        "absences",   "Absences"},
    {"\uD83D\uDCCA  Statistiques",    "stats",      "Statistiques"},
};

    for (String[] item : items) {
        final String pName = item[1];
        final String pTitle = item[2];
        JMenuItem mi = new JMenuItem(item[0]);
        mi.setForeground(TEXT_PRIMARY);
        mi.setBackground(BG_CARD);
        mi.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        mi.setBorder(new EmptyBorder(10, 20, 10, 60));
        mi.setOpaque(true);
        mi.addActionListener(new ActionListener() {
    public void actionPerformed(ActionEvent evt) {
        cardLayout.show(centerPanel, pName);
        lblCurrentPage.setText(pTitle + "  ");
    }
});
        mi.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent e) { mi.setBackground(new Color(56,139,253,80)); }
            public void mouseExited (MouseEvent e) { mi.setBackground(BG_CARD); }
        });
        popup.add(mi);
        if (!item[1].equals("stats")) {
            JSeparator sep = new JSeparator();
            sep.setForeground(BORDER_COLOR);
            popup.add(sep);
        }
    }

    // Bouton central
    JButton btnNav = new JButton("\u2630  Navigation  \u25be");
    btnNav.setForeground(TEXT_PRIMARY);
    btnNav.setFont(new Font("Segoe UI", Font.BOLD, 13));
    btnNav.setBackground(new Color(48, 54, 61));
    btnNav.setOpaque(true);
    btnNav.setContentAreaFilled(true);
    btnNav.setBorderPainted(false);
    btnNav.setFocusPainted(false);
    btnNav.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    btnNav.setPreferredSize(new Dimension(200, 42));
    btnNav.addActionListener(e -> popup.show(btnNav, 0, btnNav.getHeight()));

    JPanel center = new JPanel(new FlowLayout(FlowLayout.CENTER, 0, 4));
    center.setOpaque(false);
    center.add(btnNav);
    nav.add(center, BorderLayout.CENTER);

    // Badge droite
    lblCurrentPage = new JLabel("Employ\u00e9s  ");
    lblCurrentPage.setFont(FONT_SMALL);
    lblCurrentPage.setForeground(ACCENT_BLUE);
    lblCurrentPage.setOpaque(true);
    lblCurrentPage.setBackground(new Color(56, 139, 253, 25));
    lblCurrentPage.setBorder(new EmptyBorder(4, 12, 4, 16));
    nav.add(lblCurrentPage, BorderLayout.EAST);

    nav.setPreferredSize(new Dimension(0, 52));
    return nav;
}

    // ── Panel Employés ────────────────────────────────────────────────────
    private JPanel creerPanelEmployes() {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBackground(BG_DARK);
        panel.add(creerSidebar(
            "👤", "Employés", "Gestion des employés",
            new String[]{"NOM", "DÉPARTEMENT", "POSTE"},
            new ModernTextField[]{
                txtEmpNom         = new ModernTextField("ex: Dupont"),
                txtEmpDepartement = new ModernTextField("ex: Informatique"),
                txtEmpPoste       = new ModernTextField("ex: Développeur")
            },
            ACCENT_BLUE,
            () -> actionEmpAjouter(),
            () -> actionEmpModifier(),
            () -> actionEmpSupprimer(),
            () -> actionEmpActualiser(),
            s  -> lblEmpStatus = s
        ), BorderLayout.WEST);

        JPanel main = new JPanel(new BorderLayout());
        main.setBackground(BG_DARK);
        main.add(creerEnteteTable("Liste des Employés", l -> lblEmpBadge = l), BorderLayout.NORTH);

        modelEmployes = new DefaultTableModel(new String[]{"Nom","Département","Poste","ID"}, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        tblEmployes = creerTableStylee(modelEmployes);
        cacherColonne(tblEmployes, 3);

        tblEmployes.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                selEmp = tblEmployes.getSelectedRow();
                if (selEmp >= 0) {
                    txtEmpNom        .setText((String) modelEmployes.getValueAt(selEmp, 0));
                    txtEmpDepartement.setText((String) modelEmployes.getValueAt(selEmp, 1));
                    txtEmpPoste      .setText((String) modelEmployes.getValueAt(selEmp, 2));
                }
            }
        });
        main.add(enveloperTable(tblEmployes), BorderLayout.CENTER);
        panel.add(main, BorderLayout.CENTER);
        return panel;
    }

    private void actionEmpAjouter() {
        String nom  = txtEmpNom.getText().trim();
        String dep  = txtEmpDepartement.getText().trim();
        String post = txtEmpPoste.getText().trim();
        if (nom.isEmpty() || dep.isEmpty()) { setStatut(lblEmpStatus, "Nom et département obligatoires", ACCENT_RED); return; }
        if (!new EmployeDAO().ajouter(new Employe(nom, dep, post))) { setStatut(lblEmpStatus, "Erreur BDD", ACCENT_RED); return; }
        actionEmpActualiser();
        viderChamps(txtEmpNom, txtEmpDepartement, txtEmpPoste);
        setStatut(lblEmpStatus, "Employé ajouté ✓", ACCENT_GREEN);
    }

    private void actionEmpModifier() {
        if (selEmp < 0) { setStatut(lblEmpStatus, "Sélectionnez une ligne", ACCENT_RED); return; }
        int id = (int) modelEmployes.getValueAt(selEmp, 3);
        String nom = txtEmpNom.getText().trim(), dep = txtEmpDepartement.getText().trim(), post = txtEmpPoste.getText().trim();
        if (!new EmployeDAO().modifier(new Employe(id, nom, dep, post))) { setStatut(lblEmpStatus, "Erreur BDD", ACCENT_RED); return; }
        actionEmpActualiser(); viderChamps(txtEmpNom, txtEmpDepartement, txtEmpPoste); selEmp = -1;
        setStatut(lblEmpStatus, "Employé modifié ✓", ACCENT_ORANGE);
    }

    private void actionEmpSupprimer() {
        if (selEmp < 0) { setStatut(lblEmpStatus, "Sélectionnez une ligne", ACCENT_RED); return; }
        if (JOptionPane.showConfirmDialog(this, "Supprimer cet employé ?", "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            int id = (int) modelEmployes.getValueAt(selEmp, 3);
            if (!new EmployeDAO().supprimer(id)) { setStatut(lblEmpStatus, "Erreur BDD", ACCENT_RED); return; }
            actionEmpActualiser(); viderChamps(txtEmpNom, txtEmpDepartement, txtEmpPoste); selEmp = -1;
            setStatut(lblEmpStatus, "Employé supprimé", ACCENT_RED);
        }
    }

    public void actionEmpActualiser() {
        if (modelEmployes == null) return;
        modelEmployes.setRowCount(0);
        List<Employe> l = new EmployeDAO().listerTous();
        for (Employe e : l) modelEmployes.addRow(new Object[]{e.getNom(), e.getDepartement(), e.getPoste(), e.getId()});
        if (lblEmpBadge != null) lblEmpBadge.setText(l.size() + " entrées");
        setStatut(lblEmpStatus, "Actualisé (" + l.size() + ")", ACCENT_GREEN);
    }

    // ── Panel Types ───────────────────────────────────────────────────────
    private JPanel creerPanelTypes() {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBackground(BG_DARK);
        panel.add(creerSidebar(
            "📋", "Types d'Absence", "Catégories",
            new String[]{"LIBELLÉ"},
            new ModernTextField[]{ txtTypeLibelle = new ModernTextField("ex: Maladie") },
            ACCENT_ORANGE,
            () -> actionTypeAjouter(), () -> actionTypeModifier(),
            () -> actionTypeSupprimer(), () -> actionTypeActualiser(),
            s -> lblTypeStatus = s
        ), BorderLayout.WEST);

        JPanel main = new JPanel(new BorderLayout());
        main.setBackground(BG_DARK);
        main.add(creerEnteteTable("Types d'Absence", l -> lblTypeBadge = l), BorderLayout.NORTH);
        modelTypes = new DefaultTableModel(new String[]{"Libellé","ID"}, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        tblTypes = creerTableStylee(modelTypes);
        cacherColonne(tblTypes, 1);
        tblTypes.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) { selType = tblTypes.getSelectedRow();
                if (selType >= 0) txtTypeLibelle.setText((String) modelTypes.getValueAt(selType, 0)); }
        });
        main.add(enveloperTable(tblTypes), BorderLayout.CENTER);
        panel.add(main, BorderLayout.CENTER);
        return panel;
    }

    private void actionTypeAjouter() {
        String lib = txtTypeLibelle.getText().trim();
        if (lib.isEmpty()) { setStatut(lblTypeStatus, "Libellé obligatoire", ACCENT_RED); return; }
        if (!new TypeAbsenceDAO().ajouter(new TypeAbsence(lib))) { setStatut(lblTypeStatus, "Erreur BDD", ACCENT_RED); return; }
        actionTypeActualiser(); txtTypeLibelle.setText("");
        setStatut(lblTypeStatus, "Type ajouté ✓", ACCENT_GREEN);
    }

    private void actionTypeModifier() {
        if (selType < 0) { setStatut(lblTypeStatus, "Sélectionnez une ligne", ACCENT_RED); return; }
        int id = (int) modelTypes.getValueAt(selType, 1);
        if (!new TypeAbsenceDAO().modifier(new TypeAbsence(id, txtTypeLibelle.getText().trim()))) { setStatut(lblTypeStatus, "Erreur BDD", ACCENT_RED); return; }
        actionTypeActualiser(); txtTypeLibelle.setText(""); selType = -1;
        setStatut(lblTypeStatus, "Type modifié ✓", ACCENT_ORANGE);
    }

    private void actionTypeSupprimer() {
        if (selType < 0) { setStatut(lblTypeStatus, "Sélectionnez une ligne", ACCENT_RED); return; }
        if (JOptionPane.showConfirmDialog(this, "Supprimer ?", "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            int id = (int) modelTypes.getValueAt(selType, 1);
            if (!new TypeAbsenceDAO().supprimer(id)) { setStatut(lblTypeStatus, "Erreur BDD", ACCENT_RED); return; }
            actionTypeActualiser(); txtTypeLibelle.setText(""); selType = -1;
            setStatut(lblTypeStatus, "Type supprimé", ACCENT_RED);
        }
    }

    public void actionTypeActualiser() {
        if (modelTypes == null) return;
        modelTypes.setRowCount(0);
        List<TypeAbsence> l = new TypeAbsenceDAO().listerTous();
        for (TypeAbsence t : l) modelTypes.addRow(new Object[]{t.getLibelle(), t.getId()});
        if (lblTypeBadge != null) lblTypeBadge.setText(l.size() + " types");
        setStatut(lblTypeStatus, "Actualisé (" + l.size() + ")", ACCENT_GREEN);
    }

    // ── Panel Absences ────────────────────────────────────────────────────
    private JPanel creerPanelAbsences() {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBackground(BG_DARK);

        JPanel sidebar = new JPanel(new BorderLayout()) {
            @Override protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setPaint(new GradientPaint(0,0,BG_PANEL,0,getHeight(),new Color(17,22,30)));
                g2.fillRect(0,0,getWidth(),getHeight());
                g2.setColor(BORDER_COLOR); g2.drawLine(getWidth()-1,0,getWidth()-1,getHeight());
                g2.dispose();
            }
        };
        sidebar.setPreferredSize(new Dimension(240, 0)); sidebar.setOpaque(false);

        JPanel logo = new JPanel(new BorderLayout());
        logo.setOpaque(false); logo.setBorder(new EmptyBorder(24,20,12,20));
        JLabel ic = new JLabel("📅"); ic.setFont(new Font("Dialog",Font.PLAIN,30)); logo.add(ic,BorderLayout.NORTH);
        JLabel tl = new JLabel("<html><b>Absences</b><br><span style='color:#8b949e;font-size:10px'>Enregistrement & filtrage</span></html>");
        tl.setForeground(TEXT_PRIMARY); tl.setBorder(new EmptyBorder(6,0,0,0)); logo.add(tl,BorderLayout.CENTER);
        sidebar.add(logo, BorderLayout.NORTH);

        JScrollPane sp = new JScrollPane(creerFormulaireAbsence());
        sp.setBorder(null); sp.setOpaque(false); sp.getViewport().setOpaque(false);
        sidebar.add(sp, BorderLayout.CENTER);

        JPanel statusP = new JPanel(new BorderLayout());
        statusP.setOpaque(false); statusP.setBorder(new EmptyBorder(8,16,16,16));
        lblAbsStatus = new JLabel("Prêt");
        lblAbsStatus.setFont(FONT_SMALL); lblAbsStatus.setForeground(TEXT_MUTED);
        lblAbsStatus.setIcon(creerPoint(ACCENT_GREEN)); lblAbsStatus.setIconTextGap(6);
        statusP.add(lblAbsStatus);
        sidebar.add(statusP, BorderLayout.SOUTH);
        panel.add(sidebar, BorderLayout.WEST);

        JPanel main = new JPanel(new BorderLayout());
        main.setBackground(BG_DARK);
        main.add(creerEnteteTable("Liste des Absences", l -> lblAbsBadge = l), BorderLayout.NORTH);

        modelAbsences = new DefaultTableModel(
            new String[]{"Employé","Département","Poste","Type","Date début","Date fin","Nb jours","ID","id_emp","id_type"}, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        tblAbsences = creerTableStylee(modelAbsences);
        for (int i = 7; i <= 9; i++) cacherColonne(tblAbsences, i);

        tblAbsences.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                selAbs = tblAbsences.getSelectedRow();
                if (selAbs >= 0) {
                    txtAbsDebut.setText((String) modelAbsences.getValueAt(selAbs, 4));
                    txtAbsFin  .setText((String) modelAbsences.getValueAt(selAbs, 5));
                    selectionnerComboEmp ((int)modelAbsences.getValueAt(selAbs, 8));
                    selectionnerComboType((int)modelAbsences.getValueAt(selAbs, 9));
                    setStatut(lblAbsStatus, "Ligne sélectionnée", ACCENT_BLUE);
                }
            }
        });
        main.add(enveloperTable(tblAbsences), BorderLayout.CENTER);
        panel.add(main, BorderLayout.CENTER);
        return panel;
    }

    private JPanel creerFormulaireAbsence() {
        JPanel p = new JPanel();
        p.setOpaque(false); p.setLayout(new BoxLayout(p, BoxLayout.Y_AXIS));
        p.setBorder(new EmptyBorder(8,16,8,16));

        ajouterSectionLabel(p, "SAISIE");
        ajouterFieldLabel(p, "EMPLOYÉ");
        cmbEmploye = new JComboBox<>(); stylerCombo(cmbEmploye); p.add(cmbEmploye); p.add(Box.createVerticalStrut(8));
        ajouterFieldLabel(p, "TYPE");
        cmbType = new JComboBox<>(); stylerCombo(cmbType); p.add(cmbType); p.add(Box.createVerticalStrut(8));
        ajouterFieldLabel(p, "DATE DÉBUT");
        txtAbsDebut = creerChamp("2024-01-01"); p.add(txtAbsDebut); p.add(Box.createVerticalStrut(8));
        ajouterFieldLabel(p, "DATE FIN");
        txtAbsFin = creerChamp("2024-01-05"); p.add(txtAbsFin); p.add(Box.createVerticalStrut(14));
        ajouterBoutonsCRUD(p, ()->actionAbsAjouter(), ()->actionAbsModifier(), ()->actionAbsSupprimer(), ()->actionAbsActualiser());

        ajouterSep(p);
        ajouterSectionLabel(p, "FILTRAGE PAR PÉRIODE");
        ajouterFieldLabel(p, "DU");
        txtFiltreDebut = creerChamp("yyyy-MM-dd"); p.add(txtFiltreDebut); p.add(Box.createVerticalStrut(8));
        ajouterFieldLabel(p, "AU");
        txtFiltreFin = creerChamp("yyyy-MM-dd"); p.add(txtFiltreFin); p.add(Box.createVerticalStrut(8));
        ajouterFieldLabel(p, "TYPE");
        cmbFiltreType = new JComboBox<>(); stylerCombo(cmbFiltreType); p.add(cmbFiltreType); p.add(Box.createVerticalStrut(8));
        ModernButton btnFiltrer = new ModernButton("🔍 Filtrer", ACCENT_BLUE, FONT_BTN);
        btnFiltrer.setAlignmentX(Component.LEFT_ALIGNMENT); btnFiltrer.setMaximumSize(new Dimension(Integer.MAX_VALUE,38));
        p.add(btnFiltrer); p.add(Box.createVerticalStrut(6));
        btnFiltrer.addActionListener(e -> actionAbsFiltrer());

        ajouterSep(p);
        ajouterSectionLabel(p, "ABSENCES SIMULTANÉES");
        ajouterFieldLabel(p, "DATE");
        txtFiltreDate = creerChamp("yyyy-MM-dd"); p.add(txtFiltreDate); p.add(Box.createVerticalStrut(8));
        ModernButton btnSim = new ModernButton("👁 Vérifier", ACCENT_PURPLE, FONT_BTN);
        btnSim.setAlignmentX(Component.LEFT_ALIGNMENT); btnSim.setMaximumSize(new Dimension(Integer.MAX_VALUE,38));
        p.add(btnSim); p.add(Box.createVerticalStrut(6));
        btnSim.addActionListener(e -> actionAbsSimultanees());
        return p;
    }

    private void actionAbsAjouter() {
        try {
            Employe emp = (Employe) cmbEmploye.getSelectedItem();
            TypeAbsence t = (TypeAbsence) cmbType.getSelectedItem();
            if (emp==null||t==null){setStatut(lblAbsStatus,"Sélectionnez employé et type",ACCENT_RED);return;}
            Date dd=SDF.parse(txtAbsDebut.getText().trim()), df=SDF.parse(txtAbsFin.getText().trim());
            if (df.before(dd)){setStatut(lblAbsStatus,"Date fin avant date début!",ACCENT_RED);return;}
            if (!new AbsenceDAO().ajouter(new Absence(dd,df,emp.getId(),t.getId()))){setStatut(lblAbsStatus,"Erreur BDD",ACCENT_RED);return;}
            actionAbsActualiser(); setStatut(lblAbsStatus, "Absence ajoutée ✓", ACCENT_GREEN);
        } catch (Exception ex) { setStatut(lblAbsStatus, "Format date: yyyy-MM-dd", ACCENT_RED); }
    }

    private void actionAbsModifier() {
        if (selAbs<0){setStatut(lblAbsStatus,"Sélectionnez une ligne",ACCENT_RED);return;}
        try {
            int id=(int)modelAbsences.getValueAt(selAbs,7);
            Employe emp=(Employe)cmbEmploye.getSelectedItem(); TypeAbsence t=(TypeAbsence)cmbType.getSelectedItem();
            Date dd=SDF.parse(txtAbsDebut.getText().trim()), df=SDF.parse(txtAbsFin.getText().trim());
            if (!new AbsenceDAO().modifier(new Absence(id,dd,df,emp.getId(),t.getId()))){setStatut(lblAbsStatus,"Erreur BDD",ACCENT_RED);return;}
            actionAbsActualiser(); selAbs=-1; setStatut(lblAbsStatus,"Absence modifiée ✓",ACCENT_ORANGE);
        } catch (Exception ex){setStatut(lblAbsStatus,"Format date: yyyy-MM-dd",ACCENT_RED);}
    }

    private void actionAbsSupprimer() {
        if (selAbs<0){setStatut(lblAbsStatus,"Sélectionnez une ligne",ACCENT_RED);return;}
        if (JOptionPane.showConfirmDialog(this,"Supprimer cette absence ?","Confirmation",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
            int id=(int)modelAbsences.getValueAt(selAbs,7);
            if (!new AbsenceDAO().supprimer(id)){setStatut(lblAbsStatus,"Erreur BDD",ACCENT_RED);return;}
            actionAbsActualiser(); selAbs=-1; setStatut(lblAbsStatus,"Absence supprimée",ACCENT_RED);
        }
    }

    public void actionAbsActualiser() {
        remplirAbsences(new AbsenceDAO().listerTous());
        chargerCombos();
    }

    private void actionAbsFiltrer() {
        String dd=txtFiltreDebut.getText().trim(), df=txtFiltreFin.getText().trim();
        Object sel=cmbFiltreType.getSelectedItem();
        Integer idType=(sel instanceof TypeAbsence)?((TypeAbsence)sel).getId():null;
        List<Absence> l=new AbsenceDAO().listerAvecFiltres(dd.equals("yyyy-MM-dd")?null:dd,df.equals("yyyy-MM-dd")?null:df,idType,null);
        remplirAbsences(l); setStatut(lblAbsStatus,"Filtre: "+l.size()+" résultats",ACCENT_BLUE);
    }

    private void actionAbsSimultanees() {
        String date=txtFiltreDate.getText().trim();
        if (date.isEmpty()||date.equals("yyyy-MM-dd")){setStatut(lblAbsStatus,"Entrez une date",ACCENT_RED);return;}
        List<Absence> l=new AbsenceDAO().absencesSimultanees(date);
        remplirAbsences(l); setStatut(lblAbsStatus,l.size()+" absents le "+date,ACCENT_PURPLE);
    }

    private void remplirAbsences(List<Absence> liste) {
        if (modelAbsences==null) return;
        modelAbsences.setRowCount(0);
        for (Absence ab : liste)
            modelAbsences.addRow(new Object[]{ab.getNomEmploye(),ab.getDepartementEmploye(),ab.getPosteEmploye(),
                ab.getLibelleType(),SDF.format(ab.getDateDebut()),SDF.format(ab.getDateFin()),
                ab.getNbJours()+" j",ab.getId(),ab.getIdEmploye(),ab.getIdType()});
        if (lblAbsBadge!=null) lblAbsBadge.setText(liste.size()+" absences");
    }

    private void chargerCombos() {
        if (cmbEmploye==null) return;
        cmbEmploye.removeAllItems();
        for (Employe e : new EmployeDAO().listerTous()) cmbEmploye.addItem(e);
        cmbType.removeAllItems();
        if (cmbFiltreType!=null){cmbFiltreType.removeAllItems();cmbFiltreType.addItem("Tous");}
        for (TypeAbsence t : new TypeAbsenceDAO().listerTous()){cmbType.addItem(t);if(cmbFiltreType!=null)cmbFiltreType.addItem(t);}
    }

    private void selectionnerComboEmp(int id) {
        for (int i=0;i<cmbEmploye.getItemCount();i++) if(cmbEmploye.getItemAt(i).getId()==id){cmbEmploye.setSelectedIndex(i);return;}
    }

    private void selectionnerComboType(int id) {
        for (int i=0;i<cmbType.getItemCount();i++) if(cmbType.getItemAt(i).getId()==id){cmbType.setSelectedIndex(i);return;}
    }

    // ── Panel Statistiques ────────────────────────────────────────────────
    private JPanel creerPanelStats() {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBackground(BG_DARK);
        panel.add(creerEnteteTable("Statistiques des Absences", l->{}), BorderLayout.NORTH);

        JPanel content = new JPanel(new GridLayout(1,2,20,0));
        content.setBackground(BG_DARK); content.setBorder(new EmptyBorder(20,20,20,20));

        DefaultTableModel mStats = new DefaultTableModel(new String[]{"Employé","Total jours"},0){@Override public boolean isCellEditable(int r,int c){return false;}};
        for (Object[] row : new AbsenceDAO().joursParEmploye()) mStats.addRow(row);
        JPanel leftPanel = new JPanel(new BorderLayout()); leftPanel.setBackground(BG_DARK);
        JLabel lEmp=new JLabel("Jours par Employé"); lEmp.setFont(new Font("Segoe UI",Font.BOLD,15));
        lEmp.setForeground(TEXT_PRIMARY); lEmp.setBorder(new EmptyBorder(0,0,10,0));
        leftPanel.add(lEmp,BorderLayout.NORTH); leftPanel.add(enveloperTable(creerTableStylee(mStats)),BorderLayout.CENTER);
        content.add(leftPanel);

        List<Object[]> statsMois = new AbsenceDAO().joursParMois();
        JPanel graphPanel = new JPanel(new BorderLayout()); graphPanel.setBackground(BG_DARK);
        JLabel lMois=new JLabel("Jours d'Absence par Mois"); lMois.setFont(new Font("Segoe UI",Font.BOLD,15));
        lMois.setForeground(TEXT_PRIMARY); lMois.setBorder(new EmptyBorder(0,0,10,0));
        graphPanel.add(lMois,BorderLayout.NORTH);

        JPanel graph = new JPanel() {
            @Override protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2=(Graphics2D)g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
                if (statsMois.isEmpty()){g2.setColor(TEXT_MUTED);g2.setFont(FONT_SMALL);g2.drawString("Aucune donnée",20,getHeight()/2);g2.dispose();return;}
                int margin=40,bottom=getHeight()-40;
                int barW=Math.max(10,(getWidth()-margin*2)/statsMois.size()-8);
                int max=1; for(Object[] r:statsMois) max=Math.max(max,(int)r[1]);
                g2.setColor(BORDER_COLOR); g2.drawLine(margin,20,margin,bottom); g2.drawLine(margin,bottom,getWidth()-10,bottom);
                int x=margin+6; Color[] colors={ACCENT_BLUE,ACCENT_GREEN,ACCENT_ORANGE,ACCENT_PURPLE,ACCENT_RED}; int ci=0;
                for (Object[] row:statsMois) {
                    int val=(int)row[1]; int h=(int)((double)val/max*(bottom-40));
                    Color c=colors[ci++%colors.length];
                    g2.setPaint(new GradientPaint(x,bottom-h,c,x,bottom,new Color(c.getRed(),c.getGreen(),c.getBlue(),60)));
                    g2.fillRoundRect(x,bottom-h,barW,h,4,4);
                    g2.setColor(TEXT_PRIMARY); g2.setFont(new Font("Segoe UI",Font.BOLD,10));
                    g2.drawString(String.valueOf(val),x+barW/2-5,bottom-h-4);
                    g2.setColor(TEXT_MUTED); g2.setFont(new Font("Segoe UI",Font.PLAIN,9));
                    String mois=row[0].toString().length()>7?row[0].toString().substring(5):row[0].toString();
                    g2.drawString(mois,x,bottom+14); x+=barW+8;
                }
                g2.dispose();
            }
        };
        graph.setBackground(BG_CARD); graph.setBorder(new LineBorder(BORDER_COLOR,1,true));
        graphPanel.add(graph,BorderLayout.CENTER); content.add(graphPanel);
        panel.add(content,BorderLayout.CENTER);

        JPanel bot = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        bot.setBackground(BG_DARK); bot.setBorder(new EmptyBorder(0,20,16,20));
        ModernButton btnR=new ModernButton("↺ Rafraîchir stats",ACCENT_BLUE,FONT_BTN);
        btnR.addActionListener(e->{centerPanel.remove(centerPanel.getComponent(3));centerPanel.add(creerPanelStats(),"stats");cardLayout.show(centerPanel,"stats");});
        bot.add(btnR); panel.add(bot,BorderLayout.SOUTH);
        return panel;
    }

    // ── Utilitaires UI ────────────────────────────────────────────────────
    interface LabelConsumer { void accept(JLabel l); }
    interface Callback      { void run(); }

    private JPanel creerSidebar(String emoji, String titre, String sub,
            String[] labels, ModernTextField[] fields, Color accent,
            Callback onAdd, Callback onEdit, Callback onDel, Callback onRefresh, LabelConsumer statusSetter) {
        JPanel sidebar = new JPanel(new BorderLayout()) {
            @Override protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2=(Graphics2D)g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setPaint(new GradientPaint(0,0,BG_PANEL,0,getHeight(),new Color(17,22,30)));
                g2.fillRect(0,0,getWidth(),getHeight()); g2.setColor(BORDER_COLOR);
                g2.drawLine(getWidth()-1,0,getWidth()-1,getHeight()); g2.dispose();
            }
        };
        sidebar.setPreferredSize(new Dimension(230,0)); sidebar.setOpaque(false);
        JPanel logo=new JPanel(new BorderLayout()); logo.setOpaque(false); logo.setBorder(new EmptyBorder(24,20,12,20));
        JLabel ic=new JLabel(emoji); ic.setFont(new Font("Dialog",Font.PLAIN,30)); logo.add(ic,BorderLayout.NORTH);
        JLabel tl=new JLabel("<html><b>"+titre+"</b><br><span style='color:#8b949e;font-size:10px'>"+sub+"</span></html>");
        tl.setForeground(TEXT_PRIMARY); tl.setBorder(new EmptyBorder(6,0,0,0)); logo.add(tl,BorderLayout.CENTER);
        sidebar.add(logo,BorderLayout.NORTH);
        JPanel form=new JPanel(); form.setOpaque(false); form.setLayout(new BoxLayout(form,BoxLayout.Y_AXIS)); form.setBorder(new EmptyBorder(8,16,8,16));
        ajouterSectionLabel(form,"INFORMATIONS");
        for (int i=0;i<labels.length;i++){ajouterFieldLabel(form,labels[i]);fields[i].setAlignmentX(Component.LEFT_ALIGNMENT);fields[i].setMaximumSize(new Dimension(Integer.MAX_VALUE,40));form.add(fields[i]);if(i<labels.length-1)form.add(Box.createVerticalStrut(10));}
        form.add(Box.createVerticalStrut(16)); ajouterSep(form); form.add(Box.createVerticalStrut(12));
        ajouterBoutonsCRUD(form,onAdd,onEdit,onDel,onRefresh); sidebar.add(form,BorderLayout.CENTER);
        JPanel statusP=new JPanel(new BorderLayout()); statusP.setOpaque(false); statusP.setBorder(new EmptyBorder(8,16,16,16));
        JLabel lbl=new JLabel("Prêt"); lbl.setFont(FONT_SMALL); lbl.setForeground(TEXT_MUTED);
        lbl.setIcon(creerPoint(ACCENT_GREEN)); lbl.setIconTextGap(6); statusSetter.accept(lbl); statusP.add(lbl);
        sidebar.add(statusP,BorderLayout.SOUTH);
        return sidebar;
    }

    private JPanel creerEnteteTable(String titre, LabelConsumer bc) {
        JPanel h=new JPanel(new BorderLayout()); h.setBackground(BG_PANEL);
        h.setBorder(new CompoundBorder(new MatteBorder(0,0,1,0,BORDER_COLOR),new EmptyBorder(16,28,16,28)));
        JLabel t=new JLabel(titre); t.setFont(FONT_TITLE); t.setForeground(TEXT_PRIMARY); h.add(t,BorderLayout.WEST);
        JLabel badge=new JLabel("0 entrées");
badge.setFont(FONT_SMALL); badge.setForeground(ACCENT_BLUE);
badge.setOpaque(false);
badge.setBorder(new EmptyBorder(4,10,4,10));
bc.accept(badge); h.add(badge,BorderLayout.EAST);; return h;
    }

    private JTable creerTableStylee(DefaultTableModel model) {
        JTable table=new JTable(model){@Override public Component prepareRenderer(TableCellRenderer r,int row,int col){Component c=super.prepareRenderer(r,row,col);c.setBackground(isRowSelected(row)?new Color(56,139,253,60):row%2==0?BG_CARD:BG_PANEL);c.setForeground(TEXT_PRIMARY);if(c instanceof JComponent)((JComponent)c).setBorder(new EmptyBorder(0,12,0,12));return c;}};
        table.setFont(FONT_TABLE); table.setRowHeight(44); table.setShowGrid(false);
        table.setIntercellSpacing(new Dimension(0,0)); table.setBackground(BG_CARD);
        table.setForeground(TEXT_PRIMARY); table.setFillsViewportHeight(true); table.setBorder(null);
        JTableHeader th=table.getTableHeader(); th.setFont(new Font("Segoe UI",Font.BOLD,11));
        th.setBackground(new Color(22,27,34)); th.setForeground(TEXT_MUTED); th.setReorderingAllowed(false);
        th.setBorder(new MatteBorder(0,0,2,0,BORDER_COLOR)); th.setPreferredSize(new Dimension(0,40));
        return table;
    }

    private JScrollPane enveloperTable(JTable t) {
    JScrollPane sp = new JScrollPane(t);
    sp.setBorder(new EmptyBorder(16, 20, 20, 20));
    sp.setBackground(BG_DARK);
    sp.getViewport().setBackground(BG_CARD);
    sp.getViewport().setBorder(null);
    sp.setViewportBorder(null);
    return sp;
}
    private void cacherColonne(JTable t,int col){t.getColumnModel().getColumn(col).setMinWidth(0);t.getColumnModel().getColumn(col).setMaxWidth(0);t.getColumnModel().getColumn(col).setWidth(0);}

    private void ajouterBoutonsCRUD(JPanel p,Callback onAdd,Callback onEdit,Callback onDel,Callback onRefresh){
        ModernButton a=new ModernButton("+ Ajouter",ACCENT_BLUE,FONT_BTN);
        ModernButton m=new ModernButton("~ Modifier",ACCENT_ORANGE,FONT_BTN);
        ModernButton s=new ModernButton("x Supprimer",ACCENT_RED,FONT_BTN);
        ModernButton r=new ModernButton("@ Actualiser",new Color(48,54,61),FONT_BTN);
        for(ModernButton b:new ModernButton[]{a,m,s,r}){b.setAlignmentX(Component.LEFT_ALIGNMENT);b.setMaximumSize(new Dimension(Integer.MAX_VALUE,38));p.add(b);p.add(Box.createVerticalStrut(6));}
        a.addActionListener(e->onAdd.run()); m.addActionListener(e->onEdit.run());
        s.addActionListener(e->onDel.run()); r.addActionListener(e->onRefresh.run());
    }

    private ModernTextField creerChamp(String ph){ModernTextField f=new ModernTextField(ph);f.setAlignmentX(Component.LEFT_ALIGNMENT);f.setMaximumSize(new Dimension(Integer.MAX_VALUE,40));return f;}
    private void ajouterSectionLabel(JPanel p,String txt){JLabel l=new JLabel(txt);l.setFont(new Font("Segoe UI",Font.BOLD,10));l.setForeground(TEXT_MUTED);l.setAlignmentX(Component.LEFT_ALIGNMENT);p.add(l);p.add(Box.createVerticalStrut(8));}
    private void ajouterFieldLabel(JPanel p,String txt){JLabel l=new JLabel(txt);l.setFont(new Font("Segoe UI",Font.BOLD,10));l.setForeground(TEXT_MUTED);l.setAlignmentX(Component.LEFT_ALIGNMENT);p.add(l);p.add(Box.createVerticalStrut(4));}
    private void ajouterSep(JPanel p){JSeparator sep=new JSeparator();sep.setForeground(BORDER_COLOR);sep.setMaximumSize(new Dimension(Integer.MAX_VALUE,1));p.add(sep);p.add(Box.createVerticalStrut(12));}
    private void stylerCombo(JComboBox<?> cb){cb.setBackground(new Color(20,25,32));cb.setForeground(TEXT_PRIMARY);cb.setFont(new Font("Segoe UI",Font.PLAIN,13));cb.setBorder(new LineBorder(BORDER_COLOR,1,true));cb.setMaximumSize(new Dimension(Integer.MAX_VALUE,40));cb.setAlignmentX(Component.LEFT_ALIGNMENT);}
    private void setStatut(JLabel lbl,String msg,Color c){if(lbl!=null){lbl.setText(msg);lbl.setIcon(creerPoint(c));}}
    private void viderChamps(ModernTextField...fields){for(ModernTextField f:fields)f.setText("");}
    private Icon creerPoint(final Color color){return new Icon(){public void paintIcon(Component c,Graphics g,int x,int y){Graphics2D g2=(Graphics2D)g.create();g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);g2.setColor(color);g2.fillOval(x,y+2,8,8);g2.dispose();}public int getIconWidth(){return 10;}public int getIconHeight(){return 12;}};}

    private void appliquerStyleGlobal(){
        UIManager.put("Menu.background",BG_PANEL); UIManager.put("Menu.foreground",TEXT_PRIMARY);
        UIManager.put("MenuBar.background",BG_PANEL); UIManager.put("MenuItem.background",BG_PANEL);
        UIManager.put("MenuItem.foreground",TEXT_PRIMARY); UIManager.put("PopupMenu.background",BG_PANEL);
        UIManager.put("OptionPane.background",BG_PANEL); UIManager.put("Panel.background",BG_PANEL);
        UIManager.put("OptionPane.messageForeground",TEXT_PRIMARY);
    }

    // ══════════════════════════════════════════════════════════════════════
    //  Variables declaration - do not modify
    // ══════════════════════════════════════════════════════════════════════
    // End of variables declaration

    /**
     * @param args the command line arguments
     */
// ══════════════════════════════════════════════════════════════════════
    //  ✅ ÉTAPE 6 : Main — remplacer l'ancien main par celui-ci
    // ══════════════════════════════════════════════════════════════════════
   public static void main(String args[]) {
    try {
        UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
    } catch (Exception ignored) {}

    java.awt.EventQueue.invokeLater(() -> {
       new LoginGUI().setVisible(true);
   
    });
}
}

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

